# Generated by Django 2.2.5 on 2020-01-02 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configurations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.Configuration')),
            ],
        ),
    ]
